name: Build a Zato quickstart container

on:
  push:
    branches:
      - 'main'
  schedule:
    # Every day at 03:17 AM
    - cron: "17 3 * * *"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zato-run-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: zatosource/zato-3.2:latest
          run: echo "Hello from Zato"
