name: Build a Zato quickstart container

on:
  push:
    branches:
      - 'main'
  schedule:
    # Every day at 05:17 AM
    - cron: "17 5 * * *"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zato-run-docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - run: docker run ghcr.io/zatosource/zato-3.2-quickstart:latest
